'use strict';
const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH || 'playwright');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:900}});
 await context.route('**/firebase-config.js',route=>route.fulfill({status:200,contentType:'application/javascript',body:"window.SHOW_CONFIG={mode:'local',room:'astra-browser-test',firebase:{},submitUrl:'',qrImage:''};"}));
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base='http://127.0.0.1:8766/';
 await page.goto(base+'stage.html');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('4 筆'));
 await page.screenshot({path:'/tmp/astra-selection.png'});
 assert.equal(await page.locator('.cast-card').count(),9);
 assert.equal(await page.locator('#start').isDisabled(),true);
 await page.locator('.cast-card').nth(0).click();await page.locator('.cast-card').nth(1).click();
 await page.locator('#start').click();await page.keyboard.press('Space');
 assert.equal(await page.locator('#actorName').textContent(),'兔子');
 await page.keyboard.press('Space');assert.equal(await page.locator('#actorName').textContent(),'柏文');
 await page.waitForTimeout(250);await page.screenshot({path:'/tmp/astra-profile.png'});
 assert.equal(await page.locator('#focusBtn').count(),0);
 assert.equal(await page.locator('#memberTags button').count(),2);
 assert.equal(await page.locator('#soundBtn').textContent(),'抽題音效：開');
 assert.equal(await page.locator('.tinder-logo').first().textContent(),'jinder');
 await page.locator('[data-member="0"]').click();
 assert.equal(await page.locator('#actorName').textContent(),'兔子');
 const firstTags=await page.locator('#tags').textContent();
 await page.locator('[data-member="0"]').click();
 assert.notEqual(await page.locator('#tags').textContent(),firstTags);
 await page.locator('[data-member="1"]').click();
 assert.equal(await page.locator('#actorName').textContent(),'柏文');
 assert.equal(await page.locator('#actorPhoto').evaluate(e=>e.complete && e.naturalWidth>0),true);
 for(let i=2;i<=7;i++){
   await page.keyboard.press(String(i+1));await page.waitForTimeout(220);
   assert.equal(await page.locator('.scene.active').getAttribute('data-scene'),String(i));
 }
 await page.keyboard.press('4');const message=await page.locator('[data-answer="3"]').textContent();
 await page.keyboard.press('8');assert.equal(typeof await page.locator('[data-answer="7"]').textContent(),'string');
 const sharedMessage=await page.locator('[data-answer="7"]').textContent();
 assert.notEqual(sharedMessage,message);
 await page.keyboard.press('6');await page.keyboard.press('6');
 await page.waitForTimeout(250);await page.screenshot({path:'/tmp/astra-story-new.png'});
 await page.keyboard.press('7');assert.equal(typeof await page.locator('#albumImage').getAttribute('src'),'string');
 await page.keyboard.press('4');await page.keyboard.press('4');
 assert.equal(await page.locator('.swipe-scene,.lock-scene,#tinderImage,.chat-date,#ambientText').count(),0);
 assert.equal(await page.locator('.anonymous-avatar svg').count(),1);
 assert.equal(await page.locator('.story-avatar').getAttribute('aria-label'),'匿名限動頭像');
 assert.equal(await page.locator('img.story-avatar,.story-avatar img').count(),0);
 assert.equal(await page.getByText('我的生活，不只有一面。',{exact:true}).count(),0);
 await page.keyboard.press('7');
 await page.waitForFunction(()=>{const e=document.querySelector('#albumImage');return e.complete&&e.naturalWidth>0;});
 await page.waitForTimeout(250);await page.screenshot({path:'/tmp/astra-album.png'});
 const submit=await context.newPage();submit.on('pageerror',e=>errors.push(e.message));
 await submit.goto(base+'submit.html');
 const values={table:'B20',nick:'測試',tag1:'一',tag2:'二',tag3:'三',romanticGesture:'用計算機算飯錢',awkwardLine:'這是測試紙條',location:'台北',igStory:'今天不想出門'};
 for(const [id,value] of Object.entries(values))await submit.locator('#'+id).fill(value);
 await submit.locator('#photo').setInputFiles('/tmp/astra-selection.png');
 await submit.waitForFunction(()=>!document.querySelector('#submitBtn').disabled);
 await submit.locator('#submitBtn').click();await submit.locator('#done').waitFor({state:'visible'});
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('5 筆'));
 const peek=await context.newPage();await peek.goto(base+'peek-k7x2.html');
 await peek.waitForFunction(()=>document.querySelector('#status').textContent.includes('5 筆'));
 await peek.getByRole('button',{name:'聊天／金句',exact:true}).click();
 assert.equal(await peek.getByText('這是測試紙條',{exact:false}).count(),1);
 await page.keyboard.press('c');await page.locator('#toggleOpen').click();
 await submit.locator('#again').click();await submit.locator('#submitBtn').click();
 await submit.getByText('投稿已截止',{exact:true}).waitFor();
 await page.locator('#toggleOpen').click();await page.keyboard.press('c');
 await page.keyboard.press('4');await page.waitForTimeout(250);await page.screenshot({path:'/tmp/astra-chat-final.png'});
 await page.locator('#profileBtn').click();
 assert.equal(await page.locator('#selection').isVisible(),true);
 assert.equal(await page.locator('.cast-card.selected').count(),0);
 assert.equal(await page.locator('#memberTags').isVisible(),false);
 await page.locator('.cast-card').nth(2).click();await page.locator('.cast-card').nth(8).click();
 await page.locator('#start').click();
 await page.keyboard.press('h');assert.equal(await page.locator('#titleScreen').isVisible(),true);
 await page.keyboard.press('q');assert.equal(await page.locator('#qrScreen').isVisible(),true);
 // QR 頁改成左右兩張 QR（2026-09-16），原本的單一 #qrImage 已拆成 .qr-code
 assert.equal(await page.locator('.qr-code').count(),2);
 assert.equal(await page.locator('.qr-code').first().evaluate(e=>e.src.startsWith('data:image/')),true);
 assert.equal(await page.locator('.qr-code').last().evaluate(e=>e.src.startsWith('data:image/')),true);
 // 掃碼時畫面上不能出現劇名
 assert.equal(await page.locator('#top .brand').isVisible(),false);
 await page.waitForTimeout(200);await page.screenshot({path:'/tmp/astra-qr.png'});
 await page.keyboard.press('1');assert.equal(await page.locator('#actorName').textContent(),'又又');
 await page.keyboard.press('2');assert.equal(await page.locator('#actorName').textContent(),'林靖');
 assert.equal(await page.locator('#titleScreen').isVisible(),false);
 assert.equal(await page.locator('#qrScreen').isVisible(),false);
 await page.keyboard.press('3');await page.waitForTimeout(250);
 await page.screenshot({path:'/tmp/astra-romantic.png'});
 await page.keyboard.press('h');await page.screenshot({path:'/tmp/astra-title.png'});
 await page.keyboard.press('c');
 await page.locator('#trialBtn').click();
 assert.equal(await page.locator('#poolStatus').textContent(),'目前：試玩題庫 · 30 筆');
 const poolCheck=await page.evaluate(()=>{
   const textDeck=ShowCore.createDeck(()=>0.12);
   const photoDeck=ShowCore.createDeck(()=>0.12);
   const texts=Array.from({length:30},()=>textDeck.draw('awkwardLine',TRIAL_RESPONSES,r=>ShowCore.valid('awkwardLine',r.awkwardLine)).awkwardLine);
   const photos=Array.from({length:30},()=>photoDeck.draw('photo',TRIAL_RESPONSES,r=>ShowCore.valid('photo',r.photo)).photo);
   return {texts:new Set(texts).size,photos:new Set(photos).size,nextText:textDeck.draw('awkwardLine',TRIAL_RESPONSES,r=>ShowCore.valid('awkwardLine',r.awkwardLine)).awkwardLine};
 });
 assert.deepEqual({texts:poolCheck.texts,photos:poolCheck.photos},{texts:30,photos:30});
 assert.equal(typeof poolCheck.nextText,'string');
 await page.keyboard.press('Escape');
 await page.keyboard.press('7');
 await page.waitForFunction(()=>document.querySelector('#albumImage').src.includes('trial-photos/'));
 await page.waitForFunction(()=>{const e=document.querySelector('#albumImage');return e.complete&&e.naturalWidth>0;});
 await page.keyboard.press('c');
 await page.locator('#profileBtn').click();
 await page.locator('#editCast').click();await page.locator('#castEditor input').nth(0).fill('兔子測試');
 await page.locator('#saveCast').click();await page.reload();
 assert.equal(await page.getByText('兔子測試',{exact:true}).count(),1);
 const mobile=await context.newPage({viewport:{width:390,height:844}});
 await mobile.goto(base+'submit.html');
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await mobile.screenshot({path:'/tmp/astra-submit-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('PASS：7 Cue、雙主角、聊天／金句共用來源不重複、30 筆試玩題庫與相簿照片載入、投稿照片同步、後台、投稿開關、演員設定、手機寬度、無 JS 例外');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
